services:
  # Newt tunneling client service
  newt:
    # Official newt Docker image from fosrl
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    
    # Required capabilities for WireGuard tunnel and network operations
    cap_add:
      - NET_ADMIN      # Required for network interface management
      - SYS_MODULE     # Required for WireGuard kernel module operations
    
    # Load environment variables from .env file
    # Alternative: You can also define environment variables directly in this file
    # by replacing the env_file section with an environment section like this:
    # environment:
    #   - PANGOLIN_ENDPOINT=https://pangolin.th-luebeck.me
    #   - NEWT_ID=your_newt_client_id
    #   - NEWT_SECRET=your_newt_client_secret
    env_file:
      - .env
    
    
    # System configuration for WireGuard compatibility
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1  # Required for WireGuard routing