services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - .env
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1